version: "3"
services:
    apren_getx:
        image: nginx
        volumes:
            - "./nginx-config:/etc/nginx/conf.d"
            - "./build/web:/usr/share/nginx/html"
        ports:
            - "4800:80"
        restart: always
